# Generated by Django 3.1.2 on 2020-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coverUrl',
            field=models.CharField(
                default='https://vignette.wikia.nocookie.net/starwars/images/4/4c/TROSOneSheet.jpg', max_length=64),
            preserve_default=False,
        ),
    ]
