# Generated by Django 3.1.2 on 2020-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20201029_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avgRating',
        ),
        migrations.AlterField(
            model_name='ratedreview',
            name='rate',
            field=models.IntegerField(
                choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
