# Generated by Django 3.1.2 on 2020-10-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0009_auto_20201029_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedreview',
            name='movie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='by_movies', to='index.movie'),
        ),
        migrations.AlterField(
            model_name='ratedreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
