# Generated by Django 3.1.2 on 2020-10-30 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0010_auto_20201029_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlist',
            name='blockedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='banlist_banned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='banlist_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratedreview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='review_by_movies', to='index.movie'),
        ),
        migrations.AlterField(
            model_name='ratedreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='review_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
