# Generated by Django 3.1.2 on 2020-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_movie_avgrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='avgRating',
            new_name='dAvgRating',
        ),
        migrations.AddField(
            model_name='movie',
            name='uAvgRating',
            field=models.FloatField(default=0),
        ),
    ]
