# Generated by Django 3.1.2 on 2020-11-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_movie_numberreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uAvgRating',
        ),
    ]
