# Generated by Django 3.1.3 on 2020-11-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_remove_movie_uavgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedreview',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='ratedreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='banlist',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='RatedReview',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
