# Generated by Django 3.1.3 on 2020-11-12 04:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdbID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('directors', models.CharField(max_length=64)),
                ('genres', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('coverUrl', models.CharField(max_length=64)),
                ('plot', models.TextField()),
                ('cast', models.TextField()),
                ('dAvgRating', models.FloatField(default=0)),
                ('numberReviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RatedReview',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[
                 (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.CharField(max_length=500)),
                ('cDate', models.DateField(
                    default=datetime.date.today, verbose_name='Date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='review_by_movies', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='review_by_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
